[package]
name = "pdf2pngs"
version = "1.0.0"
authors = ["beltegeuse <adrien.gruson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = "*"
glib = "*"
poppler = "*"
clap = "*"